### ISSUE TITLE
adapter and/or artificial sequences at the end

### ISSUE THREAD

**Issue by tolot27** [nanoporetech/nanonet#20]
Most of the reads (from R9) have up to 18 bases of the adapter at their 5' end and also about 10-15 bases of the hairpin at the 3' end in addition to some artificial bases (up to 30 bases).

It's the same situation as with the reads called by Metrichor. Unfortunately, it increases assembly time exponentially because it produces artificial overlaps.

Can be the trimming somehow improved?

I'll dig into this further and will provide some conserved motifs.

I also know that Nick Lomen does some trimming after mapping the reads to a reference (based on the CIGAR string, as far as I know), but that's not a real option because it is only applicable if a close reference is available.

**Comment by cjw85** [comment]
There are no plans to implement this in nanonet beyond the current trimming or events before basecalling. You may wish to look at https://github.com/rrwick/Porechop.
