### ISSUE TITLE
OSX install problems

### ISSUE THREAD

**Issue by mattloose** [nanoporetech/nanonet#22]
Looks like there is an absolute path somewhere:
---

This Source Code Form is subject to the terms of the Mozilla Public
License, v. 2.0. If a copy of the MPL was not distributed with this
file, You can obtain one at http://mozilla.org/MPL/2.0/.

(c) 2016 Oxford Nanopore Technologies Ltd.
---

System is Darwin
By default the 2D basecaller (standard and OpenCL) are not built.
To enable these use 'with2d' and 'opencl2d' command line options.

Adding OSX compile/link options
Setting up OpenCL 2D basecall extension, this may need some tinkering
running install
Checking .pth file support in /Library/Python/2.7/site-packages/
/usr/bin/python -E -c pass
TEST PASSED: /Library/Python/2.7/site-packages/ appears to support .pth files
running bdist_egg
running egg_info
writing requirements to nanonet.egg-info/requires.txt
writing nanonet.egg-info/PKG-INFO
writing top-level names to nanonet.egg-info/top_level.txt
writing dependency_links to nanonet.egg-info/dependency_links.txt
writing entry points to nanonet.egg-info/entry_points.txt
reading manifest file 'nanonet.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'docs'
writing manifest file 'nanonet.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.11-intel/egg
running install_lib
running build_py
copying nanonet/nanonetcall.py -> build/lib.macosx-10.11-intel-2.7/nanonet
error: Error: setup script specifies an absolute path:

**Comment by cjw85** [comment]
Hi @mattloose. I've had this before but I cannot remember what the resolution was. In can't reproduce this on my MacBook, I have python, pip et. al. installed via brew. I will see if I can reproduce on a more vanilla Mac.

**Comment by cjw85** [comment]
We've not been able to reproduce this on any of our MacBooks (with various versions of OSX/MacOS). We'll keep trying.

**Comment by mattloose** [comment]
Hmm - it might be something to do with my laptop. We had this before on the dev version of nanonet that was on GitHub and I think you posted a solution there. But that seems to have gone now...

Matt

**Comment by cjw85** [comment]
You might find what you are looking for in the resolved issues of this repository, it was easier to rename than move all the commits ;).

**Comment by mattloose** [comment]
Ah - just looked - but not sure its the same issue. However I will check. Something screwed up my laptop recently (possible cough brew cough) and I need to check!

Thanks

**Comment by cjw85** [comment]
@mattloose Did you manage to get things working again? If there's something we can do in the setup.py to cater for more setups we can add it (or you can submit a PR).

**Comment by mattloose** [comment]
Sorry for the delay in replying - finally worked out (I think) what the issue was. I had somehow installed multiple conflicting versions of hdf5 - clearing those out and reverting to brew version has (for now) fixed issues.
