### ISSUE TITLE
Nanonet2d installation error

### ISSUE THREAD

**Issue by genotypic** [nanoporetech/nanonet#23]
Dear Team ONT

We have successfully downloaded nanonet basecaller, but we could not install in out machine. We are getting following error
"ImportError: cannot import name viterbi_2d"

Kindly sort out the issue, Looking forward from you.

**Comment by cjw85** [comment]
Hi @genotypic,

The module viterbi_2d is not installed by default (see https://github.com/nanoporetech/nanonet#installation for further information), as it requires additional dependencies than the simpler 1D basecaller.

Could you provide more information concerning your operating system and what commands you have used to install and run the program? We then should be able to assist you further.

**Comment by cjw85** [comment]
Hi @genotypic 
Have you managed to make the 2D caller work for you?

**Comment by cjw85** [comment]
@genotypic 
I presume you have solved this problem, so will close the Issue. Please reopen and provide further details if this is not the case.

**Comment by genotypic** [comment]
No we could not solve the issue and still we are getting the same error.

OS used - Linux Ubuntu 14.04 

Command used for installation 
python setup.py install
make
make install

but not managed 2d caller to work. how to make caller_2d to work?

Thanks
Genotypic

**Comment by cjw85** [comment]
The installation notes https://github.com/nanoporetech/nanonet#installation and https://github.com/nanoporetech/nanonet#2d-basecalling describe how to install the 2D basecaller.

On Ubuntu you will likely wish to run:

    sudo apt-get install libboost-python1.54-dev libboost-python1.54.0`
    python setup.py install with2d

**Comment by genotypic** [comment]
Thanks for your immediate response

But now I am getting the below error

Traceback (most recent call last):
  File "/usr/local/bin/nanonet2d", line 11, in <module>
    load_entry_point('nanonet==2.0.0', 'console_scripts', 'nanonet2d')()
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 565, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2598, in load_entry_point
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2258, in load
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 2264, in resolve
  File "build/bdist.linux-x86_64/egg/nanonet/nanonetcall_2d.py", line 22, in <module>
  File "build/bdist.linux-x86_64/egg/nanonet/nanonetcall.py", line 17, in <module>
  File "build/bdist.linux-x86_64/egg/nanonet/decoding.py", line 12, in <module>
  File "build/bdist.linux-x86_64/egg/nanonet/util.py", line 36, in get_shared_lib
UnboundLocalError: local variable 'lib_file' referenced before assignment


Thanks
Genotypic

**Comment by cjw85** [comment]
Sorry about this,
The above looks like whilst running `nanonet2d` your python is importing modules from the build directory. This should not be happening. Can you remove the directory `build`?

I have run through the following on a vanilla [vagrant](https://www.vagrantup.com/) Ubuntu 14.04 virtual machine:

    sudo apt-get install -y git libboost-python1.54-dev libboost-python1.54.0 python-numpy python-setuptools python-all-dev python-h5py build-essential
    git clone http://github.com/nanoporetech/nanonet.git
    cd nanonet
    sudo python setup.py install with2d
    cd ~
    nanonet2d ~/nanonet/sample_data/ calls
    
This produces the files `calls_template.fasta`, `calls_complement.fasta`, and `calls_2d.fasta`.

**Comment by cjw85** [comment]
@genotypic Did the method above work for you?
