### ISSUE TITLE
Adapter Sequence Removal

### ISSUE THREAD

**Issue by genotypic** [nanoporetech/nanonet#24]
Hi,

Do the Nanonet 1D and 2D basecalling removes the Adapter sequences?

Regards,
Genotypic

**Comment by cjw85** [comment]
Some attempt is made to trim the event sequences to such that adapter sequences are not included in the basecall, the code for doing this is in `nanonet.segment` The process is not foolproof and it is perfectly possible that whole or partial adapter sequences will end up in the basecall.

**Comment by cjw85** [comment]
Duplicates #20
