### ISSUE TITLE
Error detected in HDF5 (1.8.11)

### ISSUE THREAD

**Issue by alantsangmb** [nanoporetech/nanonet#27]
Hi, I've just install nanonet on my Ubuntu.
And found no problem to run the sample data for both 1D and 2D call.

However, when I try on the fast5 test_reads_data provided from MinKNOW installation.

Problem occurred when 2D call attempt:

HDF5-DIAG: Error detected in HDF5 (1.8.11) thread 140086151886592:
  #000: ../../../src/H5O.c line 246 in H5Oopen(): unable to open object
    major: Symbol table
    minor: Can't open object
  #001: ../../../src/H5O.c line 1357 in H5O_open_name(): object not found
    major: Symbol table
    minor: Object not found
  #002: ../../../src/H5Gloc.c line 430 in H5G_loc_find(): can't find object
    major: Symbol table
    minor: Object not found
  #003: ../../../src/H5Gtraverse.c line 861 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #004: ../../../src/H5Gtraverse.c line 755 in H5G_traverse_real(): component not found
    major: Symbol table
    minor: Object not found
Processed 0 reads in 2.05736112595s (wall time)

====================================================
Also, although there is no warning for 1D call, no reads was returned:

Basecalled 0 reads (0 bases, 0 events) in 0.0293881893158s (wall time)

Any idea about this? Thanks

**Comment by cjw85** [comment]
Hi @alantsangmb,

I will need to check that what the test_reads_data provided with MinKnow contain. nanonet contains a directory `sample_data` which can be used for testing. Can you try running nanonet with these files?

nanonet is compatible with the read files that MinKnow produces during an ordinary run.

**Comment by alantsangmb** [comment]
Hi @cjw85 
Yes, the sample data of nanonet can be called successfully for both 1D and 2D call.

But the mention error occurred when I tried on the MAP5-CTC data downloaded from Metrichor.
This set of test reads data can also been found in the /grouper/test_reads_data/ after MinKNOW installation.

Does nanonet support the fast5 files generated from the latest R9.4 flowcell (SQK-LSK208) 2D kit?

**Comment by cjw85** [comment]
nanonet supports files from the current release of MinKnow (the sequencing kit used should be irrelevant).

nanonet does not currently have the Recurrent Neural Network configs (and some other ancillary analyses) to support optimally R9.4 with the 2D kit. We have forthcoming basecaller releases that will more optimally support the R9.4 2D kits.
