### ISSUE TITLE
Overloaded tasks? 

### ISSUE THREAD

**Issue by noncodo** [nanoporetech/nanonet#29]
I have submitted some local base calling, and it seems that nanonet (basecall2d) is eating up processes like Cookie Monster at a bake sale. 
Basic command looks like : 
`nanonet2d --jobs 8 --fastq /folder prefix`
Yet the load average is >>48 (1032 here) for the 6 concurrent jobs running on one node of our HPC. 
Any advice would be appreciated to rectify this issue. 

```
qstat -f
all.q@omega-0-17.local         BP    0/48/64        **1032.87**  lx26-amd64    a
5128451 0.12754 NANOnet    noncodo       r     11/14/2016 17:21:34     8 3
5128451 0.12754 NANOnet    noncodo       r     11/14/2016 17:21:34     8 4
5128451 0.12754 NANOnet    noncodo       r     11/14/2016 17:21:34     8 5
5128451 0.12754 NANOnet    noncodo       r     11/14/2016 17:21:34     8 6
5128451 0.12754 NANOnet    noncodo       r     11/14/2016 17:21:34     8 7
5128451 0.12754 NANOnet    noncodo       r     11/14/2016 17:21:34     8 8
```

**Comment by cjw85** [comment]
The intention is that `nanonetcall_2d` should start `--jobs` worker processes (there will also be the initial process running which is left to perform IO). Per read a worker will start a 2-thread pool to process the template and complement sections.

We can take a look if there is something nefarious happening outside of this intention.

**Comment by noncodo** [comment]
I think a closer inspection is needed, as no other jobs were running on this node. I suspect it has to do with simultaneous execution of nanonet2d commands.  
I should mention that these concurrent nanonet2d jobs were launched on a partitioned set of fast5 reads from the same run.

**Comment by cjw85** [comment]
Are you using a multithreaded BLAS? As in the [benchmarks](https://github.com/nanoporetech/nanonet#benchmarks) you can try disabling threading in the matrix routines.

**Comment by noncodo** [comment]
I did not specify the OMP_NUM_THREADS variable; I will try again with this = 1.  
FYI, the jobs were launched on a SGE cluster with smp parallel environment.

**Comment by cjw85** [comment]
@noncodo Have you been able to rationalize your load averages?

**Comment by noncodo** [comment]
I think OMP_NUM_THREADS=1 solved it, but I git distracted and didn't monitor the run closely. Will report back shortly.

**Comment by noncodo** [comment]
Confirmed, OMP_NUM_THREADS=1  saves the day :)
