### ISSUE TITLE
Quality scores explanation

### ISSUE THREAD

**Issue by danarte** [nanoporetech/nanonet#30]
Hello, I noticed that different output fastq files had exclusively different values (for example: the complement fastq file had values between *-2 while the fastq file from 2d had values between 0-7, I checked only briefely the files with a text editor so there might be more to it but that is the general trend I noticed) 
I then checked this repo and saw it had a thread on this topic: https://github.com/nanoporetech/nanonet/issues/8
based on the graphs in the comments there are really different values for each fastq file.

Could someone explain to me the exact separation of the quality scores between the different fastq files? Also are the values comparable between the different fastq files? so a value of "2" in the 2d fastq means "more accurate" basecall then a value of "0" in complement fastq file?

Thanks

**Comment by cjw85** [comment]
The quality scores for all types of call (template, complement, 2D) are scaled according to the standard phred definition: Q = -10 log P, where P is the probability of error. As such quality scores should be comparable across reads.

The fact that different quality score ranges are observed for template and complement (and 2D) is a consequence of the tendency of template reads to be more accurate than complement reads, more specifically that the basecaller is more confident in its calls of template data.

**Comment by danarte** [comment]
Thanks for the fast replay. I thought this was the case but it seemed strange that the numberes are so low compared to other ngs data. Also the fact that very small group of values is used confused me.

I would like to use this opportunity and a about

**Comment by danarte** [comment]
About albacore, the thread I linked to in the first post has a reference to a repo for albacore but it's closed. I also saw albacore was mentioned in nanopore forum recently but I couldnt find any actual software page for it. How could I get albacore?

**Comment by cjw85** [comment]
The albacore source is not currently open to all. If you wish to have access please contact our customer support.
