### ISSUE TITLE
Error while testing on sample data

### ISSUE THREAD

**Issue by shubhakar** [nanoporetech/nanonet#31]
Hey,

I followed the installation steps given and installed the simple version without 2D extension. When I tried to run the sample_data, I ended up in the following error:

```
Shubhakars-MacBook-Air:nanonet-master SReddy$ nanonetcall sample_data/ > basecall.fa 
Traceback (most recent call last):
    File "/usr/local/bin/nanonetcall", line 9, in <module>
        load_entry_point('nanonet==2.0.0', 'console_scripts', 'nanonetcall')()
        File "build/bdist.macosx-10.12-intel/egg/nanonet/nanonetcall.py", line 488, in main
        File "build/bdist.macosx-10.12-intel/egg/nanonet/nanonetcall.py", line 485, in <dictcomp>
    AttributeError: 'Namespace' object has no attribute 'sloika_model'
```

Then I tried on 'with2d' option next and the installation completed along with all dependencies but with many warnings about implicit conversion:

```
In file included from nanonet/caller_2d/common/stub_py.cpp:5:
    nanonet/caller_2d/common/view_numpy_arrays.h:48:16: warning: implicit conversion loses integer precision: 'npy_intp' (aka 'long') to 'int' [-Wshorten-64-to-32]
    int length = PyArray_DIM(obj, 0);
```

Another warning was:

`c++ -bundle -undefined dynamic_lookup -arch i386 -arch x86_64 -Wl,-F. build/temp.macosx-10.12-intel-2.7/nanonet/caller_2d/pair_align/pair_align_py.o build/temp.macosx-10.12-intel-2.7/nanonet/caller_2d/pair_align/nw_align.o build/temp.macosx-10.12-intel-2.7/nanonet/caller_2d/pair_align/mm_align.o -lboost_python-mt -o build/lib.macosx-10.12-intel-2.7/nanonet/caller_2d/pair_align/pair_align.so
ld: warning: ignoring file /usr/local/lib/libboost_python-mt.dylib, file was built for x86_64 which is not the architecture being linked (i386): /usr/local/lib/libboost_python-mt.dylib
building 'nanonet.caller_2d.common.stub' extension`

Then I tried 2D base calling on sample_data and I ended up with a ZeroDivisionError error:

```
Shubhakars-MacBook-Air:nanonet-master SReddy$ nanonet2d sample_data/ calls
    Processed 2 reads in 45.86281991s (wall time)
    Traceback (most recent call last):
    File "/usr/local/bin/nanonet2d", line 9, in <module>
    load_entry_point('nanonet==2.0.0', 'console_scripts', 'nanonet2d')()
    File "build/bdist.macosx-10.12-intel/egg/nanonet/nanonetcall_2d.py", line 263, in main
ZeroDivisionError: float division by zero
```

I am unable to figure out where is the issue. Kindly provide some help over this. Looking forward to your reply.

**Comment by mattloose** [comment]
I've just had the 'sloika_model' error as well... that's a new one on me.

**Comment by cjw85** [comment]
The `sloika_model` error is a new one introduced last week when enabling the `--chemistry` option: the error appears when this option isn't given.

@shubhakar You errors with running 2D might be related, since some default analysis parameters have been altered, and they will not be correct for the sample data. We'll look into this.

**Comment by cjw85** [comment]
I've pushed a commit which should resolved the `sloika_model` and divide-by-zeros when 2D basecalling fails.

@shubhakar Your compile warnings should be nothing to worry about. We do like do have our code compile without warnings, however. Can you give me details of the compiler you are using? On my Macbook with Xcode/clang, I do not see any compiler warnings.

**Comment by shubhakar** [comment]
@cjw85 Thanks a lot for the help!

I tried installation on two machines and both had similar warnings.
One has CentOS with `gcc 4.5.3` and other is macOS Sierra with `i686-apple-darwin11-gcc-4.2.1 (GCC) 4.2.1 (Apple Inc. build 5666)`
