### ISSUE TITLE
About Nanonettrain

### ISSUE THREAD

**Issue by woodydon** [nanoporetech/nanonet#32]
Dear Team ONT,

I am interested in using nanonettrain to train my own RNN model. I will have nanopore data from synthetic RNAs and hope to know how to label the sequences. I hope to know more about how to use nanonettrain.

Thanks,
Woody

**Comment by cjw85** [comment]
Hi @woodydon,

We do not currently offer any squiggle-to-sequence alignment tools (though this may change in future). To get started in sequence labelling you may wish to look at @jts's tools at https://github.com/jts/nanopolish, though these I believe would require a pre-existing alignment model. These will start to appear when we make our first release of our RNA sequencing chemistry (https://nanoporetech.com/publications/nanopores-allow-direct-sequencing-full-length-rna-strands-and-modified-rna-nucleotides).

Alternatively you may wish to

**Comment by woodydon** [comment]
Hi @cjw85 ,

Thanks for suggestions! I would like to learn the alternative approach that you were suggesting. The sentence is not finished.

Woody

**Comment by cjw85** [comment]
I've now finished my sentence!

**Comment by woodydon** [comment]
Hi @cjw85,

Thanks! Could you also comment on the file format (alignment model) for feeding nanonettrain?

Woody

**Comment by cjw85** [comment]
In short code requires a per-event (kmer) label. The function here: https://github.com/nanoporetech/nanonet/blob/master/nanonet/features.py#L162 takes in its arguments two functions: one for reading events and one for reading labels. The implementation of these can be changed to read data from any source (e.g. bam files from nanopolish eventalign).
