### ISSUE TITLE
quality filtering 

### ISSUE THREAD

**Issue by noncodo** [nanoporetech/nanonet#33]
It would be nice to have a built-in quality filtering parameter, much like the local base calling output produced by MinKNOW, where "pass" and "fail" folders would be generated based on the average quality scores.

**Comment by cjw85** [comment]
Hi @noncodo,

Its unlikely that we will implement this feature in nanonet. You may however request it as a feature to our production-ready Albacore basecaller via the Nanopore Community or customer support.

**Comment by noncodo** [comment]
Thanks for the reply. Sadly, we're running CentOS--not sure I want to attempt porting a .deb across distros. Guess I'll have to make due with some ad hoc scripts.

**Comment by emilhaegglund** [comment]
@noncodo, you could always try to run the albacore basecaller using a docker.
