### ISSUE TITLE
Labelled Fast5 Format for Nanonettrain

### ISSUE THREAD

**Issue by scottgigante** [nanoporetech/nanonet#34]
Hi,

I am looking at doing some RNN training using Nanonettrain but can't seem to get the format of my labelled fast5 files quite right. Is it possible to provide a sample labelled dataset?

Thanks!
Scott Gigante

**Comment by cjw85** [comment]
Hi @scottgigante,

On the issue below you will find some discussion and pointers to code that you may wish to modify:

https://github.com/nanoporetech/nanonet/issues/32

**Comment by scottgigante** [comment]
Thanks very much @cjw85 . I was intending on manipulating my data to fit your functions but I'll have a go at manipulating the functions to fit my data instead. I'll close this issue and re-open the other one if I have further comments on that approach.
