### ISSUE TITLE
nanonettrain

### ISSUE THREAD

**Issue by rojinsafavi** [nanoporetech/nanonet#39]
Hello,

I would like to install nanonettrain on our linux server. I was wondering if I still need to follow the installation protocol written in "TRAIN_INSTALL.md"? or following the installation written in README will automatically install the whole package now? I would also like to know what package/library was used to create RNN? Is it TensorFlow?

Thanks!

**Comment by cjw85** [comment]
nanonettrain comprises data wrangling scripts for preprocessing input files/datasets for input into currennt, a rather old software package from before the recent surge in popularity of neural networks. Following TRAIN_INSTALL is still required to install currennt (you can skip the parts related to installing nanonet if you have already followed the README).
