### ISSUE TITLE
installing currennt

### ISSUE THREAD

**Issue by rojinsafavi** [nanoporetech/nanonet#40]
When I follow the following steps on our linux server( I do not have root access):

#> cd currennt
#> mkdir build && cd build
#> cmake ..
#> make

I get at error at make step:

/soe/rojinsafavi/anaconda2/bin/../lib/gcc/x86_64-unknown-linux-gnu/4.8.5/../../../../lib/libnetcdf.so: undefined reference to `H5Tget_member_type'
/soe/rojinsafavi/anaconda2/bin/../lib/gcc/x86_64-unknown-linux-gnu/4.8.5/../../../../lib/libnetcdf.so: undefined reference to `H5Fget_obj_count'
/soe/rojinsafavi/anaconda2/bin/../lib/gcc/x86_64-unknown-linux-gnu/4.8.5/../../../../lib/libnetcdf.so: undefined reference to `H5Gget_objinfo'
/soe/rojinsafavi/anaconda2/bin/../lib/gcc/x86_64-unknown-linux-gnu/4.8.5/../../../../lib/libnetcdf.so: undefined reference to `SDgetfillvalue'
collect2: error: ld returned 1 exit status
make[2]: *** [currennt] Error 1
make[1]: *** [CMakeFiles/currennt.dir/all] Error 2
make: *** [all] Error 2
[rojinsafavi@citrisdance build]$

and if I execute make in the ~/currennt directory instead of building directory I get this:

/usr/bin/ld: cannot open output file currennt: Is a directory
collect2: error: ld returned 1 exit status
make[2]: *** [currennt] Error 1
make[1]: *** [CMakeFiles/currennt.dir/all] Error 2
make: *** [all] Error 2

I was wondering if I can get some help.

Thanks!

**Comment by cjw85** [comment]
I have commented on your related issue https://github.com/nanoporetech/currennt/issues/4
