### ISSUE TITLE
Python 3 compatible code ?

### ISSUE THREAD

**Issue by ishaanpbs** [nanoporetech/nanonet#42]
Does the nanonet compile on python3 ?

**Comment by cjw85** [comment]
We have a branch: https://github.com/nanoporetech/nanonet/tree/python3. Its relatively untested but should be mostly functional for 1D basecalling at least.

**Comment by cjw85** [comment]
@ishaanpbs 
Have you tried the python3 branch?

**Comment by khyox** [comment]
@cjw85, thanks for the porting. Hopefully, I'll be testing this code.

**Comment by khyox** [comment]
I'm trying to use OpenCL for the test sample_data > basecalls.fa. 
First, `nanonetcall --list_platforms` is working fine:

> ============================================================
OpenCL Platforms and Devices
============================================================
Name:     Apple
Vendor:   Apple
Version:  OpenCL 1.2 (Nov  1 2016 21:34:57)
    --------------------------------------------------------
    Name:  Iris Pro
    Type:  GPU
    Max Clock Speed:  1200 Mhz
    Compute Units:  40
    --------------------------------------------------------
    Name:  GeForce GT 750M
    Type:  GPU
    Max Clock Speed:  925 Mhz
    Compute Units:  2

With no `--exc_opencl` but `--jobs 4 --platforms apple:1:1` I get:

    NotImplementedError: Heterogeneous computer requires Python2.7.

Finally, with `--jobs 4 --platforms apple:1:1 --exc_opencl` I get

    Traceback (most recent call last):
    File "/.../3.5/bin/nanonetcall", line 11, in <module>
        load_entry_point('nanonet==2.0.0', 'console_scripts', 'nanonetcall')()
    File "/.../nanonet/nanonetcall.py", line 563, in main
    File "/.../nanonet/nanonetcall.py", line 396, in process_read_opencl
    File "/.../numpy/lib/npyio.py", line 419, in load
        pickle_kwargs=pickle_kwargs)
    File "/.../numpy/lib/format.py", line 646, in read_array
        "to numpy.load" % (err,))
    UnicodeError: Unpickling a python object failed: UnicodeDecodeError('ascii',......)
    You may need to pass the encoding= option to numpy.load

Any other combination like `apple:0:1` is giving the same error. Only `--platforms *:*:0` is doing nothing (with no error):

    Basecalled 0 reads (0 bases, 0 events) in 7e-05s (wall time)

I don't know whether OpenCL is supported under Python3. Maybe I am missing something.

**Comment by cjw85** [comment]
@khyox The python3 branch has had limited testing, hence why it has not been merged, this includes the OpenCL code path. It's unlikely that we will resolve this, but would welcome a PR, it doesn't look like the error above is anything to do with OpenCL per se.

Can I ask why you would like to use the OpenCL code? With the devices you have available above, I would recommend using the latest version of Albacore, which will likely be faster.

**Comment by khyox** [comment]
@cjw85 Thank you very much for your kind reply and help. We will be more than glad to be able to contribute with PR's as soon as we get used to the ONT ecosystem.

Sorry, we were not using Albacore because, AFAIK, it is currently not available for OS X. In addition, when I wrote my comment two weeks ago, we had not been given access to the private ONT repositories yet. After the signing of the Development Licence Agreement (which took some time), we were finally given access yesterday, so I _see_ Albacore now. Anyway, we appreciate a lot that nanonet is distributed under the open-source MPL.
