### ISSUE TITLE
qscores

### ISSUE THREAD

**Issue by ragak** [nanoporetech/nanonet#43]
Hi, I notice that the qscores that come out of nanonet and metrichor are very different (specifically in dynamic range - with metrichor providing a much wider range of scores). Can you briefly explain why that is, or point me to the pertinent part of the calculation of the qscore in the nanonet source code that causes the difference?
Thank you!

**Comment by cjw85** [comment]
Hi @ragak 

We've recently updated nanonet with some amendments to the qscore calculation. This may have explained some of the discrepancy. The core of the calculation is performed here:

https://github.com/nanoporetech/nanonet/blob/master/nanonet/nanonetcall.py#L271

The methodology within Albacore is similar, though the implementation will be different.
