### ISSUE TITLE
Nanonet 1D basecalling not compatible with EPI2ME

### ISSUE THREAD

**Issue by khyox** [nanoporetech/nanonet#49]
I open this just for reference and, maybe, to be a future enhancement/addition. 

Currently, 1D basecalling with nanonet and downstream analysis with EPI2ME (e.g. WIMP) is not a choice, as EPI2ME is looking for a structure named `Basecall_1D` and Nanonet is providing `Basecall_RNN_1D`, so the reads fail to be analysed and therefore they are downloaded to the `/downloads/fail` folder.

**Comment by cjw85** [comment]
The distinction in the HDF group name was a deliberate choice, as when nanonet was written it was somewhat of a break with previous basecallers. 

Using nanonet with EPI2ME is rather outside the scope of the project as a technology demonstrator. I can only apologise again that it is still the only offline basecaller which functions on OSX available to many; though an OSX Albacore release is forthcoming.
