### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by nmiculinic** [nanoporetech/nanonet#51]
Upon installing v2.0 using
```pip2 install --user https://github.com/nanoporetech/nanonet/archive/v2.0.0.zip```

installation fails with:
```
Command "/usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/tmp/pip-9r8rti-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-kgVHLT-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-9r8rti-build/
```

Both setuptools and tokenize are availible on this platform ```python2 -u -c "import setuptools, tokenize" ```

My platform is: ```Linux protagonist 4.10.5-1-ARCH #1 SMP PREEMPT Wed Mar 22 14:42:03 CET 2017 x86_64 GNU/Linux```

**Comment by cgmcintyr** [comment]
I created a patch for this issue, see #52 to check it works on your machine

**Comment by nmiculinic** [comment]
It appears to be working!

```pip2 install --user https://github.com/nanoporetech/nanonet/archive/bbd20d1531adab135c690aaca980f105b712f486.zip```
