### ISSUE TITLE
Getting chemistry from fast5 files

### ISSUE THREAD

**Issue by nmiculinic** [nanoporetech/nanonet#54]
Is it possible to read pore chemistry data from minion fast5 read files? As I understand R9, and R9.4 aren't the same chemistry, that is the same basecaller models shouldn't be used for both. 

I want to check which chemistry does my data have, however I'm not seeing any information in fast5 upon inspection, or at least I don't know where to look.

**Comment by cjw85** [comment]
Hi @nmiculinic 

I cannot recall whether there is a direct way by merely inspecting meta data in the files, I will check with our Production people.

In the meantime you may like to try running a set of files with `--chemistry r9` and `--chemistry r9.4` to see which results in better basecalling accuracy (I'm assuming you have a reference sequence to which you can compare the basecalls).

**Comment by nmiculinic** [comment]
I see bunch information in tracking_id, including device ID, flow cell ID and protocol_run_id but I'm not sure how interpret them.

**Comment by cjw85** [comment]
Those pieces of information could be used internally by Oxford Nanopore Technologies' for identifying the chemistry used in a flowcell. I think your best hope is to enquire with the person from whom your obtained the data.
