### ISSUE TITLE
Parallel --write_events fails

### ISSUE THREAD

**Issue by nmiculinic** [nanoporetech/nanonet#55]
Upon trying --write_events in nanonet it fails with IOError, file exists, while there's no such issue in single threaded execution. 

```nanocall <..> --write_events --jobs 24 > out.fa``` 

and 
```nanocall <...> --write_events --platforms nvidia:0:1 nvidia:0:1 nvidia:0:1 --exc_opencl> out.fa```

Both fail in the similar fashion, the reason being race condition on lock file access. I assume another thread/process locks one file for reading, while other threads want to write events in it.

**Comment by cjw85** [comment]
Hi @nmiculinic 

I apologise that you are having difficulties, can you provide the exact command line you are running and the full error message? I know that others have used the `--write_events` option and multiprocessing in conjunction.

**Comment by nmiculinic** [comment]
https://i.imgur.com/prgpCpu.png

It was easier taking the screenshot since it's remote machine. Nothing special additional arguments, just dir and specifying chemistry.

**Comment by cjw85** [comment]
Are you certain that you have write permissions to the input files?

**Comment by nmiculinic** [comment]
You're right...I don't. I forgot about it. Thank you!
